spring.application.name=internship-project-1
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/ivoyant_project_db
spring.datasource.username=postgres
spring.datasource.password=VIVEKRK31122002
spring.datasource.driver-class-name=org.postgresql.Driver
